import { D as push, T as head, K as push_element, M as pop_element, P as attr, G as pop, I as FILENAME } from "../../../chunks/index.js";
_page[FILENAME] = "src/routes/demo/+page.svelte";
function _page($$payload, $$props) {
  push(_page);
  head($$payload, ($$payload2) => {
    $$payload2.title = `<title>Demo - Verdict 360 Legal AI Assistant</title>`;
    $$payload2.out.push(`<meta name="description" content="Try our AI-powered legal assistant demo. Experience how Verdict 360 can help streamline legal consultations for South African law firms."/>`);
    push_element($$payload2, "meta", 14, 2);
    pop_element();
  });
  $$payload.out.push(`<div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100">`);
  push_element($$payload, "div", 17, 0);
  $$payload.out.push(`<div class="container mx-auto px-4 py-16 max-w-7xl">`);
  push_element($$payload, "div", 18, 2);
  $$payload.out.push(`<div class="text-center mb-12">`);
  push_element($$payload, "div", 19, 4);
  $$payload.out.push(`<h1 class="text-4xl font-bold text-gray-900 mb-4">`);
  push_element($$payload, "h1", 20, 6);
  $$payload.out.push(`Experience Verdict 360 AI Legal Assistant</h1>`);
  pop_element();
  $$payload.out.push(` <p class="text-xl text-gray-600 max-w-3xl mx-auto">`);
  push_element($$payload, "p", 23, 6);
  $$payload.out.push(`Chat with our AI legal assistant to see how it can help your law firm provide instant, 
        accurate legal guidance to clients 24/7.</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="grid md:grid-cols-2 gap-8 mb-12">`);
  push_element($$payload, "div", 29, 4);
  $$payload.out.push(`<div class="bg-white rounded-xl shadow-lg p-8">`);
  push_element($$payload, "div", 31, 6);
  $$payload.out.push(`<h2 class="text-2xl font-bold mb-4 text-gray-900">`);
  push_element($$payload, "h2", 32, 8);
  $$payload.out.push(`How to Use the Demo</h2>`);
  pop_element();
  $$payload.out.push(` <ol class="space-y-3 text-gray-700">`);
  push_element($$payload, "ol", 33, 8);
  $$payload.out.push(`<li class="flex items-start">`);
  push_element($$payload, "li", 34, 10);
  $$payload.out.push(`<span class="bg-blue-600 text-white rounded-full w-6 h-6 flex items-center justify-center flex-shrink-0 mr-3 text-sm">`);
  push_element($$payload, "span", 35, 12);
  $$payload.out.push(`1</span>`);
  pop_element();
  $$payload.out.push(` <span>`);
  push_element($$payload, "span", 36, 12);
  $$payload.out.push(`Click the chat widget in the bottom right corner to start</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(` <li class="flex items-start">`);
  push_element($$payload, "li", 38, 10);
  $$payload.out.push(`<span class="bg-blue-600 text-white rounded-full w-6 h-6 flex items-center justify-center flex-shrink-0 mr-3 text-sm">`);
  push_element($$payload, "span", 39, 12);
  $$payload.out.push(`2</span>`);
  pop_element();
  $$payload.out.push(` <span>`);
  push_element($$payload, "span", 40, 12);
  $$payload.out.push(`Ask any South African legal question</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(` <li class="flex items-start">`);
  push_element($$payload, "li", 42, 10);
  $$payload.out.push(`<span class="bg-blue-600 text-white rounded-full w-6 h-6 flex items-center justify-center flex-shrink-0 mr-3 text-sm">`);
  push_element($$payload, "span", 43, 12);
  $$payload.out.push(`3</span>`);
  pop_element();
  $$payload.out.push(` <span>`);
  push_element($$payload, "span", 44, 12);
  $$payload.out.push(`Get instant, context-aware legal guidance</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(` <li class="flex items-start">`);
  push_element($$payload, "li", 46, 10);
  $$payload.out.push(`<span class="bg-blue-600 text-white rounded-full w-6 h-6 flex items-center justify-center flex-shrink-0 mr-3 text-sm">`);
  push_element($$payload, "span", 47, 12);
  $$payload.out.push(`4</span>`);
  pop_element();
  $$payload.out.push(` <span>`);
  push_element($$payload, "span", 48, 12);
  $$payload.out.push(`Schedule a consultation if needed</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(`</ol>`);
  pop_element();
  $$payload.out.push(` <div class="mt-6 p-4 bg-blue-50 rounded-lg">`);
  push_element($$payload, "div", 52, 8);
  $$payload.out.push(`<p class="text-sm text-blue-800">`);
  push_element($$payload, "p", 53, 10);
  $$payload.out.push(`<strong>`);
  push_element($$payload, "strong", 54, 12);
  $$payload.out.push(`Note:</strong>`);
  pop_element();
  $$payload.out.push(` This is a demo version. In production, the AI is customized 
            for each law firm with specific practice areas and knowledge bases.</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="bg-white rounded-xl shadow-lg p-8">`);
  push_element($$payload, "div", 61, 6);
  $$payload.out.push(`<h2 class="text-2xl font-bold mb-4 text-gray-900">`);
  push_element($$payload, "h2", 62, 8);
  $$payload.out.push(`Sample Questions to Try</h2>`);
  pop_element();
  $$payload.out.push(` <ul class="space-y-3">`);
  push_element($$payload, "ul", 63, 8);
  $$payload.out.push(`<li class="flex items-start">`);
  push_element($$payload, "li", 64, 10);
  $$payload.out.push(`<svg class="w-5 h-5 text-green-500 mr-2 mt-0.5" fill="currentColor" viewBox="0 0 20 20">`);
  push_element($$payload, "svg", 65, 12);
  $$payload.out.push(`<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd">`);
  push_element($$payload, "path", 66, 14);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(` <span class="text-gray-700">`);
  push_element($$payload, "span", 68, 12);
  $$payload.out.push(`"What are the requirements for a valid will in South Africa?"</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(` <li class="flex items-start">`);
  push_element($$payload, "li", 70, 10);
  $$payload.out.push(`<svg class="w-5 h-5 text-green-500 mr-2 mt-0.5" fill="currentColor" viewBox="0 0 20 20">`);
  push_element($$payload, "svg", 71, 12);
  $$payload.out.push(`<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd">`);
  push_element($$payload, "path", 72, 14);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(` <span class="text-gray-700">`);
  push_element($$payload, "span", 74, 12);
  $$payload.out.push(`"How does divorce work under South African law?"</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(` <li class="flex items-start">`);
  push_element($$payload, "li", 76, 10);
  $$payload.out.push(`<svg class="w-5 h-5 text-green-500 mr-2 mt-0.5" fill="currentColor" viewBox="0 0 20 20">`);
  push_element($$payload, "svg", 77, 12);
  $$payload.out.push(`<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd">`);
  push_element($$payload, "path", 78, 14);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(` <span class="text-gray-700">`);
  push_element($$payload, "span", 80, 12);
  $$payload.out.push(`"What are my rights as a tenant in South Africa?"</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(` <li class="flex items-start">`);
  push_element($$payload, "li", 82, 10);
  $$payload.out.push(`<svg class="w-5 h-5 text-green-500 mr-2 mt-0.5" fill="currentColor" viewBox="0 0 20 20">`);
  push_element($$payload, "svg", 83, 12);
  $$payload.out.push(`<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd">`);
  push_element($$payload, "path", 84, 14);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(` <span class="text-gray-700">`);
  push_element($$payload, "span", 86, 12);
  $$payload.out.push(`"How do I register a company in South Africa?"</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(` <li class="flex items-start">`);
  push_element($$payload, "li", 88, 10);
  $$payload.out.push(`<svg class="w-5 h-5 text-green-500 mr-2 mt-0.5" fill="currentColor" viewBox="0 0 20 20">`);
  push_element($$payload, "svg", 89, 12);
  $$payload.out.push(`<path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd">`);
  push_element($$payload, "path", 90, 14);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(` <span class="text-gray-700">`);
  push_element($$payload, "span", 92, 12);
  $$payload.out.push(`"What is POPIA and how does it affect my business?"</span>`);
  pop_element();
  $$payload.out.push(`</li>`);
  pop_element();
  $$payload.out.push(`</ul>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="bg-white rounded-xl shadow-lg p-8 mb-12">`);
  push_element($$payload, "div", 99, 4);
  $$payload.out.push(`<h2 class="text-2xl font-bold mb-6 text-center text-gray-900">`);
  push_element($$payload, "h2", 100, 6);
  $$payload.out.push(`What Makes Our AI Special</h2>`);
  pop_element();
  $$payload.out.push(` <div class="grid md:grid-cols-3 gap-6">`);
  push_element($$payload, "div", 101, 6);
  $$payload.out.push(`<div class="text-center">`);
  push_element($$payload, "div", 102, 8);
  $$payload.out.push(`<div class="bg-blue-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">`);
  push_element($$payload, "div", 103, 10);
  $$payload.out.push(`<svg class="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">`);
  push_element($$payload, "svg", 104, 12);
  $$payload.out.push(`<path stroke-linecap="round" stroke-linejoin="round"${attr("stroke-width", 2)} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253">`);
  push_element($$payload, "path", 105, 14);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <h3 class="font-semibold mb-2">`);
  push_element($$payload, "h3", 108, 10);
  $$payload.out.push(`SA Law Trained</h3>`);
  pop_element();
  $$payload.out.push(` <p class="text-gray-600 text-sm">`);
  push_element($$payload, "p", 109, 10);
  $$payload.out.push(`Specifically trained on South African legislation, case law, and legal procedures</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="text-center">`);
  push_element($$payload, "div", 112, 8);
  $$payload.out.push(`<div class="bg-green-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">`);
  push_element($$payload, "div", 113, 10);
  $$payload.out.push(`<svg class="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">`);
  push_element($$payload, "svg", 114, 12);
  $$payload.out.push(`<path stroke-linecap="round" stroke-linejoin="round"${attr("stroke-width", 2)} d="M13 10V3L4 14h7v7l9-11h-7z">`);
  push_element($$payload, "path", 115, 14);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <h3 class="font-semibold mb-2">`);
  push_element($$payload, "h3", 118, 10);
  $$payload.out.push(`Instant Responses</h3>`);
  pop_element();
  $$payload.out.push(` <p class="text-gray-600 text-sm">`);
  push_element($$payload, "p", 119, 10);
  $$payload.out.push(`Provide immediate legal guidance to clients 24/7, reducing wait times</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="text-center">`);
  push_element($$payload, "div", 122, 8);
  $$payload.out.push(`<div class="bg-purple-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4">`);
  push_element($$payload, "div", 123, 10);
  $$payload.out.push(`<svg class="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">`);
  push_element($$payload, "svg", 124, 12);
  $$payload.out.push(`<path stroke-linecap="round" stroke-linejoin="round"${attr("stroke-width", 2)} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z">`);
  push_element($$payload, "path", 125, 14);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <h3 class="font-semibold mb-2">`);
  push_element($$payload, "h3", 128, 10);
  $$payload.out.push(`Secure &amp; Compliant</h3>`);
  pop_element();
  $$payload.out.push(` <p class="text-gray-600 text-sm">`);
  push_element($$payload, "p", 129, 10);
  $$payload.out.push(`POPIA compliant with enterprise-grade security for sensitive legal data</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` `);
  {
    $$payload.out.push("<!--[!-->");
  }
  $$payload.out.push(`<!--]-->`);
  pop();
}
_page.render = function() {
  throw new Error("Component.render(...) is no longer valid in Svelte 5. See https://svelte.dev/docs/svelte/v5-migration-guide#Components-are-no-longer-classes for more information");
};
export {
  _page as default
};
