# Development version with easier setup and hot reload

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: verdict360-postgres-dev
    environment:
      POSTGRES_DB: verdict360_dev
      POSTGRES_USER: verdict360_user
      POSTGRES_PASSWORD: verdict360_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - verdict360-dev-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: verdict360-redis-dev
    command: redis-server --appendonly yes
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - verdict360-dev-network

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    container_name: verdict360-ollama-dev
    volumes:
      - ollama_dev_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - verdict360-dev-network
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0

  # Development App (with hot reload)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: verdict360-app-dev
    environment:
      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: verdict360_dev
      DB_USER: verdict360_user
      DB_PASSWORD: verdict360_password
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # AI Service
      OLLAMA_BASE_URL: http://ollama:11434
      AI_MODEL: llama3.1:8b
      
      # Application
      NODE_ENV: development
      PORT: 3000
      
      # Client configuration  
      REACT_APP_API_URL: http://localhost:4000
      
      # JWT
      JWT_SECRET: dev_jwt_secret_for_docker
      JWT_REFRESH_SECRET: dev_refresh_secret_for_docker
      
      # Default tenant
      DEFAULT_TENANT: demo
      TENANT_DOMAIN_SUFFIX: .verdict360.local
      
    ports:
      - "4000:3000"
      - "4001:3001"  # For React dev server
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/client/node_modules
      - ./logs:/app/logs
    networks:
      - verdict360-dev-network
    depends_on:
      - postgres
      - redis
      - ollama
    command: sh -c "npm run server:dev & npm run client:dev:docker & wait"

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  ollama_dev_data:
    driver: local

networks:
  verdict360-dev-network:
    driver: bridge