import { D as push, T as head, K as push_element, M as pop_element, G as pop, I as FILENAME } from "../../chunks/index.js";
_page[FILENAME] = "src/routes/+page.svelte";
function _page($$payload, $$props) {
  push(_page);
  head($$payload, ($$payload2) => {
    $$payload2.title = `<title>Verdict 360 - AI Legal Assistant for South African Law Firms</title>`;
    $$payload2.out.push(`<meta name="description" content="Multi-tenant SaaS platform providing AI-powered legal chatbots for South African law firms. Streamline client consultations and legal advice."/>`);
    push_element($$payload2, "meta", 13, 2);
    pop_element();
  });
  $$payload.out.push(`<div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 w-full overflow-x-hidden">`);
  push_element($$payload, "div", 16, 0);
  $$payload.out.push(`<div class="container mx-auto px-4 py-16 max-w-7xl">`);
  push_element($$payload, "div", 17, 2);
  $$payload.out.push(`<div class="text-center mb-16">`);
  push_element($$payload, "div", 18, 4);
  $$payload.out.push(`<h1 class="text-5xl font-bold text-gray-900 mb-6">`);
  push_element($$payload, "h1", 19, 6);
  $$payload.out.push(`Welcome to <span class="text-blue-600">`);
  push_element($$payload, "span", 20, 19);
  $$payload.out.push(`Verdict 360</span>`);
  pop_element();
  $$payload.out.push(`</h1>`);
  pop_element();
  $$payload.out.push(` <p class="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">`);
  push_element($$payload, "p", 22, 6);
  $$payload.out.push(`The premier AI-powered legal assistant platform for South African law firms. 
        Enhance client consultations with intelligent, context-aware legal guidance.</p>`);
  pop_element();
  $$payload.out.push(` <div class="flex justify-center space-x-4">`);
  push_element($$payload, "div", 27, 6);
  $$payload.out.push(`<a href="/demo" class="bg-blue-600 text-white px-8 py-3 rounded-lg hover:bg-blue-700 transition-colors font-semibold">`);
  push_element($$payload, "a", 28, 8);
  $$payload.out.push(`Try Demo</a>`);
  pop_element();
  $$payload.out.push(` <a href="/admin" class="border border-blue-600 text-blue-600 px-8 py-3 rounded-lg hover:bg-blue-50 transition-colors font-semibold">`);
  push_element($$payload, "a", 34, 8);
  $$payload.out.push(`Admin Dashboard</a>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="grid md:grid-cols-3 gap-8 mb-16">`);
  push_element($$payload, "div", 43, 4);
  $$payload.out.push(`<div class="bg-white p-8 rounded-xl shadow-lg">`);
  push_element($$payload, "div", 44, 6);
  $$payload.out.push(`<div class="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mb-6">`);
  push_element($$payload, "div", 45, 8);
  $$payload.out.push(`<svg class="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">`);
  push_element($$payload, "svg", 46, 10);
  $$payload.out.push(`<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z">`);
  push_element($$payload, "path", 47, 12);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <h3 class="text-xl font-semibold mb-4">`);
  push_element($$payload, "h3", 50, 8);
  $$payload.out.push(`AI-Powered Consultations</h3>`);
  pop_element();
  $$payload.out.push(` <p class="text-gray-600">`);
  push_element($$payload, "p", 51, 8);
  $$payload.out.push(`Intelligent chatbot trained on South African law provides instant, accurate legal guidance to your clients.</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="bg-white p-8 rounded-xl shadow-lg">`);
  push_element($$payload, "div", 56, 6);
  $$payload.out.push(`<div class="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mb-6">`);
  push_element($$payload, "div", 57, 8);
  $$payload.out.push(`<svg class="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">`);
  push_element($$payload, "svg", 58, 10);
  $$payload.out.push(`<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-4m-5 0H3m2 0h3M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4">`);
  push_element($$payload, "path", 59, 12);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <h3 class="text-xl font-semibold mb-4">`);
  push_element($$payload, "h3", 62, 8);
  $$payload.out.push(`Multi-Tenant SaaS</h3>`);
  pop_element();
  $$payload.out.push(` <p class="text-gray-600">`);
  push_element($$payload, "p", 63, 8);
  $$payload.out.push(`Each law firm gets their own branded instance with isolated data and custom configurations.</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <div class="bg-white p-8 rounded-xl shadow-lg">`);
  push_element($$payload, "div", 68, 6);
  $$payload.out.push(`<div class="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mb-6">`);
  push_element($$payload, "div", 69, 8);
  $$payload.out.push(`<svg class="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">`);
  push_element($$payload, "svg", 70, 10);
  $$payload.out.push(`<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z">`);
  push_element($$payload, "path", 71, 12);
  $$payload.out.push(`</path>`);
  pop_element();
  $$payload.out.push(`</svg>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` <h3 class="text-xl font-semibold mb-4">`);
  push_element($$payload, "h3", 74, 8);
  $$payload.out.push(`Calendar Integration</h3>`);
  pop_element();
  $$payload.out.push(` <p class="text-gray-600">`);
  push_element($$payload, "p", 75, 8);
  $$payload.out.push(`Seamless appointment booking with Google Calendar integration and automated client notifications.</p>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  $$payload.out.push(` `);
  {
    $$payload.out.push("<!--[!-->");
  }
  $$payload.out.push(`<!--]--></div>`);
  pop_element();
  $$payload.out.push(`</div>`);
  pop_element();
  pop();
}
_page.render = function() {
  throw new Error("Component.render(...) is no longer valid in Svelte 5. See https://svelte.dev/docs/svelte/v5-migration-guide#Components-are-no-longer-classes for more information");
};
export {
  _page as default
};
